services:
  app:
    build: .
    ports:
      - "8000:8000"
    env_file: .env
    volumes:
      - .:/app
    networks:
      - shared-dev

networks:
  shared-dev:
    external: true
    name: shared-dev
