"""add sale_comps and satei_sessions tables

Revision ID: f9050cfabacd
Revises: a1c4e6b8d2f0
Create Date: 2026-06-14 08:07:32.165523
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f9050cfabacd'
down_revision: Union[str, None] = 'a1c4e6b8d2f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sale_comps',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('city_code', sa.String(), nullable=False),
    sa.Column('zip_code', sa.String(), nullable=True),
    sa.Column('ward_code', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('source_record_id', sa.String(), nullable=True),
    sa.Column('address_hint', sa.String(), nullable=True),
    sa.Column('trade_price_yen', sa.Integer(), nullable=False),
    sa.Column('unit_price_yen', sa.Integer(), nullable=True),
    sa.Column('menseki_m2', sa.Float(), nullable=True),
    sa.Column('built_year', sa.Integer(), nullable=True),
    sa.Column('construction_type', sa.String(), nullable=True),
    sa.Column('walk_minutes', sa.Integer(), nullable=True),
    sa.Column('floor_level', sa.Integer(), nullable=True),
    sa.Column('transaction_year', sa.Integer(), nullable=True),
    sa.Column('transaction_quarter', sa.Integer(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_sale_comps_city', 'sale_comps', ['city_code'], unique=False)
    op.create_index('ix_sale_comps_ward', 'sale_comps', ['ward_code'], unique=False)
    op.create_index('ix_sale_comps_zip', 'sale_comps', ['zip_code'], unique=False)
    op.create_table('satei_sessions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('property_id', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('menseki_m2', sa.Float(), nullable=True),
    sa.Column('built_year', sa.Integer(), nullable=True),
    sa.Column('construction_type', sa.String(), nullable=True),
    sa.Column('walk_minutes', sa.Integer(), nullable=True),
    sa.Column('satei_price_yen', sa.Integer(), nullable=True),
    sa.Column('confidence_low_yen', sa.Integer(), nullable=True),
    sa.Column('confidence_high_yen', sa.Integer(), nullable=True),
    sa.Column('comp_count', sa.Integer(), nullable=True),
    sa.Column('adjustment_grid', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('result_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_satei_sessions_created', 'satei_sessions', ['created_at'], unique=False)
    op.create_index('ix_satei_sessions_user', 'satei_sessions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_satei_sessions_user', table_name='satei_sessions')
    op.drop_index('ix_satei_sessions_created', table_name='satei_sessions')
    op.drop_table('satei_sessions')
    op.drop_index('ix_sale_comps_zip', table_name='sale_comps')
    op.drop_index('ix_sale_comps_ward', table_name='sale_comps')
    op.drop_index('ix_sale_comps_city', table_name='sale_comps')
    op.drop_table('sale_comps')
    # ### end Alembic commands ###
